name: Laurent Curau
meta_description: "Laurent Curau works at 8th Light and he writes about software development."

markdown: kramdown
highlighter: rouge
logo: false
baseurl: /
permalink: /:title
domain_name: 'https://laurentcurau.com'
google_analytics: 'UA-374156-4'

# Details for the RSS feed generator
url:            'laurentcurau.com'
author:         'Laurent Curau'

social:
  twitter: https://twitter.com/laurentqro
  github: https://github.com/laurentqro
  email: 'mailto:laurentcurau@gmail.com'
