name: Laurent Curau - Software Engineer
meta_description: "Laurent Curau, independent software engineer. Solving business problems with software since 2014."

markdown: kramdown
highlighter: rouge
logo: false
baseurl: /
permalink: /:title
domain_name: 'https://laurentcurau.com'
google_analytics: 'UA-374156-4'

# Details for the RSS feed generator
url:            'laurentcurau.com'
author:         'Laurent Curau'

social:
  twitter: https://twitter.com/laurentqro
  github: https://github.com/laurentqro
  email: 'mailto:hello@thecodeshed.dev'
